### ISSUE TITLE
恢复的json数据无法直接还原

### ISSUE THREAD

**Issue by ITTWTTI** [hcymysql/reverse_sql#6]
恢复的json是这种格式的，能否处理成纯json字符转
Mysql 5.7
```
`content`={b'sill': 800, b'depth': 900, b'width': 660, b'height': 2000, b'transom': 0, b'doorType': 1, b'fixedMode': 0, b'glassArea': 0, b'glassInfo': {b'sideList': [{b'perimeter': 5.085999965667725, b'sideItemId': b'1466325040665759250'}], b'slotArea': 0, b'angleList': [{b'angleTotal': 4, b'angleItemId': b'1466325040665759255'}], b'glassData': [{b'glassItemId': b'1466325040665759002', b'shapeItemId': b'1466325040665759242', b'areaMaxMeasure': 1.2400000095367432}], b'holeTotal': 0, b'holeItemId': b'', b'waterKnifeItemId': b'', b'waterKnifeBaseItemId': b''}, b'glassType': b'1463434743002759171', b'productname': b'\xe5\xb7\xa6\xe5\xbc\x80\xe9\x97\xa8(0\xe5\x9b\xba)', b'halfWallType': 1,
```

**Comment by hcymysql** [comment]
> {b'sill': 800, b'depth': 900

请问你的表结构和数据，是下面这样的吗？
```
mysql> show create table t6\G
*************************** 1. row ***************************
       Table: t6
Create Table: CREATE TABLE `t6` (
  `id` int NOT NULL,
  `content` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
1 row in set (0.00 sec)

mysql> select * from t6;
+----+-----------------------------+
| id | content                     |
+----+-----------------------------+
|  1 | {'sill': 800, 'depth': 900} |
+----+-----------------------------+
1 row in set (0.00 sec)
```

**Comment by ITTWTTI** [comment]
以下是表结构，content字段是json格式
```sql
CREATE TABLE `table` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `content` json DEFAULT NULL COMMENT '内容',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT=''


SELECT id, content FROM table;

id          content
1           {"depth":0,"height":0,"length":0,"doorPos":4000,"doorTyoe":7,"doorType":7,"material":[{"area":0,"code":"1","name":"2S","type":0,"height":0,"length":0,"codename":"name","quantity":1,"seriesId":"111","glassIndex":0,"materialId":"1234567894561231456"}]}
```

**Comment by hcymysql** [comment]
> ```sql
> CREATE TABLE `table` (
>   `id` bigint(20) NOT NULL COMMENT '主键',
>   `content` json DEFAULT NULL COMMENT '内容',
>   PRIMARY KEY (`id`) USING BTREE
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
> ```

好的，收到，我看一下。

**Comment by hcymysql** [comment]
> 恢复的json是这种格式的，能否处理成纯json字符转 Mysql 5.7
> 
> ```
> `content`={b'sill': 800, b'depth': 900, b'width': 660, b'height': 2000, b'transom': 0, b'doorType': 1, b'fixedMode': 0, b'glassArea': 0, b'glassInfo': {b'sideList': [{b'perimeter': 5.085999965667725, b'sideItemId': b'1466325040665759250'}], b'slotArea': 0, b'angleList': [{b'angleTotal': 4, b'angleItemId': b'1466325040665759255'}], b'glassData': [{b'glassItemId': b'1466325040665759002', b'shapeItemId': b'1466325040665759242', b'areaMaxMeasure': 1.2400000095367432}], b'holeTotal': 0, b'holeItemId': b'', b'waterKnifeItemId': b'', b'waterKnifeBaseItemId': b''}, b'glassType': b'1463434743002759171', b'productname': b'\xe5\xb7\xa6\xe5\xbc\x80\xe9\x97\xa8(0\xe5\x9b\xba)', b'halfWallType': 1,
> ```

你的数据库版本是？select @@version;

**Comment by ITTWTTI** [comment]
> > 恢复的json是这种格式的，能否处理成纯json字符转 Mysql 5.7
> > ```
> > `content`={b'sill': 800, b'depth': 900, b'width': 660, b'height': 2000, b'transom': 0, b'doorType': 1, b'fixedMode': 0, b'glassArea': 0, b'glassInfo': {b'sideList': [{b'perimeter': 5.085999965667725, b'sideItemId': b'1466325040665759250'}], b'slotArea': 0, b'angleList': [{b'angleTotal': 4, b'angleItemId': b'1466325040665759255'}], b'glassData': [{b'glassItemId': b'1466325040665759002', b'shapeItemId': b'1466325040665759242', b'areaMaxMeasure': 1.2400000095367432}], b'holeTotal': 0, b'holeItemId': b'', b'waterKnifeItemId': b'', b'waterKnifeBaseItemId': b''}, b'glassType': b'1463434743002759171', b'productname': b'\xe5\xb7\xa6\xe5\xbc\x80\xe9\x97\xa8(0\xe5\x9b\xba)', b'halfWallType': 1,
> > ```
> 
> 你的数据库版本是？select @@Version;

5.7.30-log

**Comment by hcymysql** [comment]
> > > 恢复的json是这种格式的，能否处理成纯json字符转 Mysql 5.7
> > > ```
> > > `content`={b'sill': 800, b'depth': 900, b'width': 660, b'height': 2000, b'transom': 0, b'doorType': 1, b'fixedMode': 0, b'glassArea': 0, b'glassInfo': {b'sideList': [{b'perimeter': 5.085999965667725, b'sideItemId': b'1466325040665759250'}], b'slotArea': 0, b'angleList': [{b'angleTotal': 4, b'angleItemId': b'1466325040665759255'}], b'glassData': [{b'glassItemId': b'1466325040665759002', b'shapeItemId': b'1466325040665759242', b'areaMaxMeasure': 1.2400000095367432}], b'holeTotal': 0, b'holeItemId': b'', b'waterKnifeItemId': b'', b'waterKnifeBaseItemId': b''}, b'glassType': b'1463434743002759171', b'productname': b'\xe5\xb7\xa6\xe5\xbc\x80\xe9\x97\xa8(0\xe5\x9b\xba)', b'halfWallType': 1,
> > > ```
> > 
> > 
> > 你的数据库版本是？select @@Version;
> 
> 5.7.30-log

哦了好。

**Comment by hcymysql** [comment]
> 恢复的json是这种格式的，能否处理成纯json字符转 Mysql 5.7
> 
> ```
> `content`={b'sill': 800, b'depth': 900, b'width': 660, b'height': 2000, b'transom': 0, b'doorType': 1, b'fixedMode': 0, b'glassArea': 0, b'glassInfo': {b'sideList': [{b'perimeter': 5.085999965667725, b'sideItemId': b'1466325040665759250'}], b'slotArea': 0, b'angleList': [{b'angleTotal': 4, b'angleItemId': b'1466325040665759255'}], b'glassData': [{b'glassItemId': b'1466325040665759002', b'shapeItemId': b'1466325040665759242', b'areaMaxMeasure': 1.2400000095367432}], b'holeTotal': 0, b'holeItemId': b'', b'waterKnifeItemId': b'', b'waterKnifeBaseItemId': b''}, b'glassType': b'1463434743002759171', b'productname': b'\xe5\xb7\xa6\xe5\xbc\x80\xe9\x97\xa8(0\xe5\x9b\xba)', b'halfWallType': 1,
> ```

https://github.com/hcymysql/reverse_sql/releases/download/reverse_sql_json/reverse_sql_mysql57
下载这个最新版，再试试，我增加了json类型支持

**Comment by hcymysql** [comment]
> > > 恢复的json是这种格式的，能否处理成纯json字符转 Mysql 5.7
> > > ```
> > > `content`={b'sill': 800, b'depth': 900, b'width': 660, b'height': 2000, b'transom': 0, b'doorType': 1, b'fixedMode': 0, b'glassArea': 0, b'glassInfo': {b'sideList': [{b'perimeter': 5.085999965667725, b'sideItemId': b'1466325040665759250'}], b'slotArea': 0, b'angleList': [{b'angleTotal': 4, b'angleItemId': b'1466325040665759255'}], b'glassData': [{b'glassItemId': b'1466325040665759002', b'shapeItemId': b'1466325040665759242', b'areaMaxMeasure': 1.2400000095367432}], b'holeTotal': 0, b'holeItemId': b'', b'waterKnifeItemId': b'', b'waterKnifeBaseItemId': b''}, b'glassType': b'1463434743002759171', b'productname': b'\xe5\xb7\xa6\xe5\xbc\x80\xe9\x97\xa8(0\xe5\x9b\xba)', b'halfWallType': 1,
> > > ```
> > 
> > 
> > 你的数据库版本是？select @@Version;
> 
> 5.7.30-log

https://github.com/hcymysql/reverse_sql/releases/download/reverse_sql_json/reverse_sql_mysql57
下载这个最新版，再试试，我增加了json类型支持

![image](https://github.com/hcymysql/reverse_sql/assets/19261879/1556f652-91e6-47e6-81c5-5b0f15f27f22)
